import type { Metadata } from "next";
import { Murecho } from "next/font/google";
import "./globals.css";
import ContainerWrapper from "@/app/Container";
import Header from "./header";

const inter = Murecho({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#ebf0f5]`}>
        <Header />
        <ContainerWrapper>
          {children}
        </ContainerWrapper>
      </body>
    </html>
  );
}
